[project]
name = "ex-basics-2"
version = "0.1"
description = "ex-basics-2 -> Script made using the rich package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "rich>=14.0.0",
]

[project.scripts]
ex-basics-2 = "ex_basics_2.main:main"