[project]
name = "shreyas-hello"
version = "1.1"
description = "ex-basics-1 -> Print hello to the argument passed or world, by default."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
shreyas-hello = "shreyas_hello.main:main"